spring:
  datasource:
    url: jdbc:mysql://db-mysq-lukasmd-do-user-9461440-0.b.db.ondigitalocean.com:25060/task-management
    username: lukasmd-app
    password: lm52fuxnbgruhizd
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  flyway:
    out-of-order: true
    locations:
      - classpath:db/migration/

# JWT
jwt:
  secret:
    key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A
  time:
    expiration: 86400000

